# Generated by Django 5.0.3 on 2024-03-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='name')),
                ('description', models.CharField(blank=True, default='', max_length=254, verbose_name='description')),
                ('image', models.ImageField(blank=True, default='', upload_to='image/', verbose_name='Image')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_data')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created_data')),
            ],
            options={
                'verbose_name': 'Image Setting',
                'verbose_name_plural': 'Image Settings',
                'ordering': ('image',),
            },
        ),
    ]
