# Generated by Django 5.0.3 on 2024-03-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_imagesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_data')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created_data')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='name')),
                ('text', models.TextField(blank=True, default='', max_length=254, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Text Setting',
                'verbose_name_plural': 'Text Settings',
                'ordering': ('text',),
            },
        ),
    ]
